comment: true
ignore:
  - "l2geth"
  - "**/*.t.sol"
  - "op-bindings/bindings/*.go"
  - "packages/contracts-bedrock/contracts/(vendor|libraries)/(trie|rlp)"
flag_management:
  # Note: flags should have the same name as the circleci job in which they
  # are uploaded.
  individual_flags:
    - name: bedrock-go-tests
    - name: contracts-bedrock-tests
      paths:
        - packages/contracts-bedrock/contracts
      statuses:
        - type: patch
          target: 100%
    - name: common-ts-tests
    - name: contracts-tests
    - name: core-utils-tests
    - name: actor-tests-tests
    - name: contracts-governance-tests
    - name: contracts-periphery-tests
    - name: dtl-tests
    - name: drippie-mon-tests
    - name: fault-detector-tests
    - name: message-relayer-tests
    - name: replica-healthcheck-tests
    - name: sdk-tests
coverage:
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        # advanced
        branches:
          - master
        if_ci_failed: error #success, error
        only_pulls: false
        flags:
          - "unit"
        paths:
          - "src"
