---
name: 'Changeset integrity checker'
on:
  - pull_request_target

jobs:
  changesets-integrity-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'changeset status'
        run: npx changeset status
