name: proxyd unit tests

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./go/proxyd

jobs:
  test:
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make proxyd

    - name: Lint
      run: make lint

    - name: Test
      run: make test
