name: Test Embedded

on: [push, pull_request]

jobs:
  unit:
    name: Test Embedded
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Go and Python
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.16 python3 python3-pip
    - name: Install Python deps
      run: pip3 install -r risc/requirements.txt
    - name: Build minigeth and run default block (cache)
      run: |
        ./run.sh
        minigeth/go-ethereum 13284491
    - name: Test in the embedded world
      run: |
        cd risc
        ./build.sh && ./run.py 
