name: 'UFM Test Service: 1 hour'

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  ufm_test_service_metamask:
    name: 'UFM Test Service: Metamask'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker-compose run metamask
        env:
          CI: ${{ secrets.CI }}
          PROMETHEUS_SERVER_URL: ${{ secrets.PROMETHEUS_SERVER_URL }}
          PROMETHEUS_PUSHGATEWAY_URL: ${{ secrets.PROMETHEUS_PUSHGATEWAY_URL }}
          METAMASK_SECRET_WORDS_OR_PRIVATEKEY: ${{ secrets.METAMASK_SECRET_WORDS_OR_PRIVATEKEY }}
          METAMASK_NETWORK: ${{ secrets.METAMASK_NETWORK || 'goerli' }}
          METAMASK_PASSWORD: ${{ secrets.METAMASK_PASSWORD || 'T3st_P@ssw0rd!' }}
          METAMASK_DAPP_URL: ${{ secrets.METAMASK_DAPP_URL || 'http://localhost:9011' }}
          METAMASK_OP_GOERLI_RPC_URL: ${{ secrets.METAMASK_OP_GOERLI_RPC_URL }}
